SRC-134: Expose pre-filters to the public API
groupby/api-javascript pull request #215
Opened 2020-03-23 20:32 UTC by JamesPace-GBI

# DO NOT MERGE

Now Bridge supports the `pre-filter` string body parameter we should include this in the Javascript API Client.

2020-03-24 12:31 UTC, HaiHoang-GBI submitted a review, later dismissed

2020-04-03 16:01 UTC, jmbtutor requested changes
The general approach looks good. There are some tweaks necessary for compatibility with our release process, as well as some minor tweaks for code style.

2020-04-03 16:01 UTC, jmbtutor commented on CHANGELOG.md
> +## [2.7.0] - 2020-03-24
The release process will add this automatically, but you need to tell it how to bump the version number:

```suggestion
## [Unreleased] [minor]
```

In the future, you can use the `scripts/add-unreleased-section.sh` script to help add this section in the proper format.

2020-04-03 16:01 UTC, jmbtutor commented on package.json
> +  "version": "2.7.0",
The release process will take care of this.
```suggestion
  "version": "2.6.2",
```

2020-04-03 16:01 UTC, jmbtutor commented on src/core/query.ts
> +    this.request['pre-filter'] = preFilterExpression;
I seem to recall this kebab-casing was intentional?

2020-04-03 16:01 UTC, jmbtutor commented on src/models/request.ts
> +    ['pre-filter']?: string;
The brackets are not needed since the value inside is a string:
```suggestion
    'pre-filter'?: string;
```

2020-04-03 16:01 UTC, jmbtutor commented on test/unit/fixtures.ts
> +  ['pre-filter']: 'brand = "shiny"',
Brackets with strings is redundant.
```suggestion
  'pre-filter': 'brand = "shiny"',
```

2020-04-03 16:05 UTC, JamesPace-GBI commented on src/core/query.ts
> +    this.request['pre-filter'] = preFilterExpression;
Yes it is, that was the desired name of the body attribute.

2020-04-03 16:24 UTC, JamesPace-GBI commented on CHANGELOG.md
> +## [2.7.0] - 2020-03-24
Thanks 👍

2020-04-03 16:44 UTC, jmbtutor approved these changes
Looks good to me.

2020-04-07 17:17 UTC, DanielMoniz-GBI approved these changes

2020-04-07 17:19 UTC, merged