BBD-97: Add customUrlParam
groupby/api-javascript pull request #49
Opened 2016-10-11 20:05 UTC by Vic-Dev

2016-10-11 20:23 UTC, Vic-Dev reviewed
hi vic-dev

2016-10-11 20:23 UTC, Vic-Dev commented on test/fixtures.ts
>  export let CUSTOM_PARAMS_FROM_STRING = [
Not used anywhere, should we still have tests in query for custom url params now that its moved to bridge or take this out?

2016-10-11 20:37 UTC, effervescentia requested changes
💰 🏭

2016-10-11 20:37 UTC, effervescentia commented on src/capacitor/index.ts
> +    customUrlParams?: any;
`queryParams`

2016-10-11 20:37 UTC, effervescentia commented on src/core/bridge.ts
> +    const queryParams = Object.assign({}, this.config['customUrlParams'], query.queryParams);
shouldn't need string literal accessor? (`['customUrlParams']`)

2016-10-11 20:37 UTC, effervescentia commented on src/core/bridge.ts
> +    const queryParams = Object.assign({}, this.config['customUrlParams'], query.queryParams);
also, we can only get `query.queryParams` in the case where type is `object` and `query instanceof Query`

2016-10-11 20:37 UTC, effervescentia commented on src/core/bridge.ts
> +        ? { request: query.build(), queryParams }
break into if statement to handle pulling `queryParams` from `query`

2016-10-11 20:37 UTC, effervescentia commented on test/fixtures.ts
>  export let CUSTOM_PARAMS_FROM_STRING = [
@Vic-Dev you can remove this

2016-10-12 03:13 UTC, effervescentia requested changes
otherwise 🔥

2016-10-12 03:13 UTC, effervescentia commented on src/core/bridge.ts
> +        ? { request: query.build(), queryParams: Object.assign({}, queryParams, query.queryParams) }
can just be `Object.assign(queryParams, query.queryParams)` as the original `queryParams` from line 71 already builds off of a new empty object

2016-10-12 14:16 UTC, merged